# Site settings
baseurl = ""
languageCode = "en-us"
title = "Security Research at the University of Melbourne"
theme = ["hugrid"]
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"
[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about hugo'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
[[menu.main]]
  name = 'getting started'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/getting-started/'
  weight = -100
[params]
    # Meta
    title = "Security Research Group at the University of Melbourne"
    subtitle = "Breaking, Fixing, and Making"
    author = ""
    description = ""
    keywords = ""

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Visit researcher profile"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']

    leadtext = """We are the CS Security Research group at the University of Melbourne. Our research includes formal methods, cryptography, systems security, and blockchains.  
    \
&nbsp;  
    To find us visit level 2 in [Melbourne Connect](https://melbconnect.com.au/).
    """